### ISSUE TITLE
why don't project_notebook.ipynb does not show whole lines of code?

### ISSUE THREAD

**Issue by saisreepothu** [shakeelr/Udacity-ND113-Route-Planner#1]
I couldn't able to complete the project. Could you please help me. my email address saisri654321@gmail.com

**Comment by shakeelr** [comment]
Hi, the code can be found in "student_code.py" if that's what you are looking for.  If you still need help after reviewing the code and comments, let me know.  This was not an easy project and it took me a couple of tries to get it working.  Good luck!

**Comment by saisreepothu** [comment]
Thanks for your reply.I had completed my project and I tried it for many
times and then I completed it .
